
// Using ESP32

#define VCCVoltage 3.3f
#define ANALOG_RES 12

// https://github.com/CDFER/esp32-Max-PWM
#define LEDC_RESOLUTION 10
#define LEDC_DUTY_MAX 1024 // 2^LEDC_RESOLUTION
#define LEDC_FREQUENCY 35000

#define CHANNEL_TACH 0
#define CHANNEL_COOL 1
#define CHANNEL_FUEL 2

#define CHANNEL_MAX_TACH 0.955
#define CHANNEL_MAX_COOL 0.8
#define CHANNEL_MAX_FUEL 0.5

// High beams, Turn signals LEDs are controlled from the car. (By using optocouplers)

// Pins:
// G36 ADC INPUT ONLY
// G39 ADC INPUT ONLY
// G34 ADC INPUT ONLY
// G35 ADC INPUT ONLY
#define PIN_TACH 32 // ADC
#define PIN_COOLANT_GAUGE 33 // ADC
#define PIN_FUEL_GAUGE 25 // ADC
#define PIN_AUDIO 26 // ADC
// G27 ADC
// G14 ADC JTAG
// G12 ADC STRAPPING PD FLASH BOOT
// G13 ADC JTAG
// G09 ADC SD Data RX1 FLASH
// G10 ADC SD Data TX1 FLASH
// G11 ADC SD CMD FLASH

// G23 SPI MOSI
// G22 I2C CLK
// G01 TX0 USB CONSOLE
// G03 RX0 USB CONSOLE
// G21 I2C DATA
// G19 SPI MISO
// G18 SPI SCK
#define PIN_CAN_CS 5 // SPI SS/CS STRAPPING BOOT SDIO SLAVE
// G17 TX2 FLASH
// G16 RX2 FLASH
#define PIN_DISPLAY_DC 4 // ADC STRAPPING BOOT CONFIG
#define PIN_DISPLAY_CS 0 // ADC STRAPPING BOOT
#define PIN_COOLANT_LED 2 // ADC STRAPPING RESET
#define PIN_BATTERY_LED 15 // ADC STRAPPING BOOT PU
// G08 SD Data FLASH
// G07 SD Data FLASH
// G31 SD CLK